import os
import pprint

known_labels = []

base = os.path.dirname(os.path.abspath(__file__))
abs_file = os.path.join(base, 'labels.txt')
with open(abs_file, 'r') as f:
    file_content = f.read()
    for line in file_content.splitlines():
        if line != '':
            if line.strip() not in known_labels:
                known_labels.append(line.strip())
known_labels = sorted(known_labels)
#pprint.pprint(known_labels)

normalized_labels = {
    '20 Buck Spin': '20 Bucks Spin',
    '666Records': '666 Records',
    '7 Degrees': '7Degrees Records',
    '7 Degrees Records': '7Degrees Records',
    '7Degrees Records': '7Degrees Records',
    '7degrees Records': '7Degrees Records',
    'AFM': 'AFM Records',
    'An Out Recordsings': 'An Out Recordings',
    'Bastardited Recordings': 'Bastardized Recordings',
    'Blood Harves': 'Blood Harvest Records',
    'Blood Harvest': 'Blood Harvest Records',
    'Blood Harvest Records': 'Blood Harvest Records',
    'Bloodharvest Records': 'Blood Harvest Records',
    'Candlelight': 'Candlelight Records',
    'Cyclon Empire': 'Cyclone Empire',
    'DB Agency': 'Delicious Bowels Agency',
    'Delicious Bowels': 'Delicious Bowels Agency',
    'Delicous Bowls': 'Delicious Bowels Agency',
    'Dark Descend': 'Dark Descent Records',
    'Dark Descent': 'Dark Descent Records',
    'Dark Descent Rec.': 'Dark Descent Records',
    'Dark Descent Records': 'Dark Descent Records',
    'Dark Essence': 'Dark Essence Records',
    'Dead Heroes': 'Dead Heroes Records',
    'Debemur Mori': 'Debemur Morti Productions',
    'Debemur Morti': 'Debemur Morti Productions',
    'Defying Dagger': 'Defying Dagger Records',
    'Defying Danger Rec.': 'Defying Dagger Records',
    'Deity Down Records': 'Deity Dawn Records',
    'Doomentia': 'Doomentia Records',
    'Earache': 'Earache Records',
    'Ecocentric': 'Ecocentric Records',
    'Eigenveröffentlichung': 'Eigenproduktion',
    'Eigenproduktion': 'Eigenproduktion',
    'Everdayhate': 'EveryDayHate',
    'Everydayhate': 'EveryDayHate',
    'Extremely Rotten': 'Extremely Rotten Productions',
    'FDA REKOTZ': 'FDA Rekotz',
    'FDA-Rekotz': 'FDA Rekotz',
    'Ferret Style': 'Ferret Style Records',
    'Fragule Branch': 'Fragile Branch',
    'Fucking Kill Records': 'Fucking Kill! Records',
    'Fysik Format': 'Fysisk Format',
    'Godeater Records': 'GodEater Records',
    'Grindattack': 'Grind Attack',
    'Grindfather Prod.': 'Grindfather Productions',
    'Grindhead-Records': 'Grindhead Records',
    'Hammerheart': 'Hammerheart Records',
    'Hecatome Records': 'Hecatombe Records',
    'Hell\'s Headbangers': 'Hells Headbangers Records',
    'Ibex Moon': 'Ibex Moon Records',
    'Impious Desecration': 'Impious Desecration Records',
    'Iron Bonehead': 'Iron Bonehead Productions',
    'Les Acteurs De L\'ombre': 'Les Acteurs De L\'ombre Productions',
    'MDD': 'MDD Records',
    'Me Saco Un Ojo': 'Me Saco Un Ojo Records',
    'Metal Blade': 'Metal Blade Records',
    'Obscure Domain': 'Obscure Domain Productions',
    'Peaceville': 'Peaceville Records',
    'Peaceville Rec.': 'Peaceville Records',
    'Power It Up': 'Power It Up!',
    'Power It Up Records': 'Power It Up!',
    'Power It Up-Records': 'Power It Up!',
    'Power it Up! Records': 'Power It Up!',
    'Power-It-Up': 'Power It Up!',
    'Power-It-Up Records': 'Power It Up!',
    'Profunde Lore': 'Profound Lore',
    'Pulverise Records': 'Pulverized Records',
    'Pulverised': 'Pulverized Records',
    'Pulverised Records': 'Pulverized Records',
    'Quam Libet Rec.': 'Quam Libet Records',
    'RTM Productions': 'Rebirth The Metal Productions',
    'Rebirth The Metal': 'Rebirth The Metal Productions',
    'Rebirth The Metal Production': 'Rebirth The Metal Productions',
    'Relapse': 'Relapse Records',
    'Rödel Rec.': 'Rödel Records',
    'SPV': 'SPV GmbH',
    'Satanath Records': 'Sathanath Records',
    'Selfmade God': 'Selfmade God Records',
    'Sepulcharl Voice Records': 'Sepulchral Voice Records',
    'Sick Man Getting Sick': 'Sick Man Getting Sick Records',
    'Visceral Circuitry': 'Visceral Circuitry Records',
    'War Antheme': 'War Anthem Records',
    'War Antheme Records': 'War Anthem Records',
    'War-Anthem Recors': 'War Anthem Records',
    'WarAntheme Records': 'War Anthem Records',
    'Waranthem Records': 'War Anthem Records',
    'Weed Hunter Records': 'Weedhunter Records',
    'Werewolf Production': 'Werewolf Productions',
    'Werewolf Produktion': 'Werewolf Productions',
    'Willowtip Records': 'Willowtip',
    'Wolfsbane Rec.':'Wolfsbane Records',
    'Wolvesbane Records':'Wolfsbane Records',
    'Wooaaargh Rec.':'Wooaaargh',
    'Wooaaargh Records':'Wooaaargh',
    'Woooaargh':'Wooaaargh',
    'Xtreme Music': 'Xtreem Music',
}
